name: Run The Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Unit Testing
      run: |
        cd CourseManagementService
        python manage.py test
    - name: Build and push the image
      run: |
        docker login --username mysoladi --password ${{secrets.ACCESS_TOKEN}} ghcr.io
        docker build -t ghcr.io/mysoladi/course-management-service:latest --file Dockerfile .
        docker push ghcr.io/mysoladi/course-management-service:latest
