# Generated by Django 4.2.7 on 2024-03-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='None', max_length=400),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.TextField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channels',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending course that has not been approved by system admin'), ('Approved', 'Approved course that has not yet began'), ('Denied', 'Denied course'), ('Active', 'Ongoing course'), ('Concluded', 'Course that has concluded')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
